### ISSUE TITLE
Peer names are not stored in the zocp node

### ISSUE THREAD

**Issue by fieldOfView** [z25/pyZOCP#43]
Since the recent Pyre update, peer names are no longer stored in the capability tree. Instead, names live in the Pyre land, and are sent with all messages.

There are still usecases where it is useful to be able to know the name of a peer, for example when compiling a list of all current peers in the network (and presenting this to the user in a friendlier way than though the uuids).

Perhaps if names do not belong in the capability-tree (ie: stored in ```peers_capabilities```), there could be a ```peers_names``` dict?

**Comment by sphaero** [comment]
So the reply from the zmq devs was that you should track names yourself as you already receive them through the ENTER event. So this is not going to happen in Pyre either.

**Comment by fieldOfView** [comment]
Ok, I'll continue using that workaround.
