### ISSUE TITLE
Unify QT examples; PyQt5 license

### ISSUE THREAD

**Issue by fieldOfView** [z25/pyZOCP#66]
@ikbenmacje committed a PySide/Qt4 example to the examples folder. It would be trivial to create a single, unified Qt example that uses a try/catch around the import statements and uses whatever is available.

What is the status of PyQt5? Can we use it in the pyZOCP repo? Last I heard from @sphaero is that there may be a LGPL/GPL conflict. It looks like there is still an issue and we may have to remove the Qt5 example.

**Comment by sphaero** [comment]
I think we can. Our examples are also GPL so there is no issue. When other licenses popup we'd have look into it but until then. I'm not sure how that holds with ZOCP and its parents...

Perhaps this helps? http://www.gnu.org/cgi-bin/license-quiz.cgi

**Comment by fieldOfView** [comment]
See https://github.com/z25/pyZOCP/pull/67

**Comment by fieldOfView** [comment]
> Perhaps this helps? http://www.gnu.org/cgi-bin/license-quiz.cgi

No, not even a bit

**Comment by fieldOfView** [comment]
Would someone please look at https://github.com/z25/pyZOCP/pull/67?

**Comment by fieldOfView** [comment]
Fixed here: https://github.com/z25/pyZOCP/pull/67
